crud_django/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clientes/', include('exemplo.urls')),
]

exemplo/urls.py
from django.urls import path
from exemplo import views

app_name = 'exemplo'

urlpatterns = [
    path('', views.ClienteList.as_view(), name='list'),
    path('create/', views.ClienteCreate.as_view(), name='create')
]

exemplo/models.py
from django.db import models

class Cliente (models.Model):
    nome = models.CharField(max_length=30)
    idade = models.IntegerField(blank=True, null=True)
    
    def __str__(self):
        return self.nome

exemplo/forms.py
from django import forms

from exemplo.models import Cliente

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente 
        fields = '__all__'

exemplo/views.py
# from django.shortcuts import render
from django.views.generic import ListView, CreateView
from django.urls import reverse_lazy
from exemplo.models import Cliente

class ClienteList(ListView):
    model = Cliente
    queryset = Cliente.objects.all()  # método que será utilizado para buscar os clientes
    
class ClienteCreate(CreateView):
    model = Cliente
    fields = '__all__'
    success_url = reverse_lazy('exemplo:list')

templates/exemplo/cliente_form.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html lang='pt-br'>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Cadastro</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h1>Cadastro de Clientes</h1>
        <form method='post' action='.'>
            {% csrf_token %}
            {{ form.as_p }}
            <input type='submit' value='salvar'>
            <input type='reset' value='cancelar' onclick="location.href = '{% url 'exemplo:list' %}'"/>
        </form>
        
        <script src="" async defer></script>
    </body>
</html>

templates/exemplo/cliente_list.html
<!DOCTYPE html>

<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Lista de Clientes</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h1>Lista de clientes</h1>
        <input type='submit' value='Adicionar usuário' onclick="location.href = '{% url 'exemplo:create' %}'">
        <ul>
            {% for cliente in object_list %}
                <li>{{ cliente.nome }} </li>
            {% endfor %}
        </ul>
        <script src="" async defer></script>
    </body>
</html>